# Generated by Django 3.0.6 on 2020-05-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sltDashboardApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('total_limit', models.IntegerField()),
                ('total_used', models.IntegerField()),
                ('day_limit', models.IntegerField()),
                ('day_used', models.IntegerField()),
            ],
        ),
    ]
